### PR TITLE
Fix issues

### PR DESCRIPTION
**Pull request by tsegismont**
Fix remaining issues

Follows-up on #1 and #2

### CODE REVIEW

**Comment by tsegismont** [comment]
@vietj it seems I cannot push to main branch on this repo so I had to create this PR

**Comment by tsegismont** [comment]
@vietj main branch has been built and artifacts uploaded :rocket:

**Comment by vietj** [comment]
so we can merge vertx-core PR now, is that right ?

**Comment by tsegismont** [comment]
> so we can merge vertx-core PR now, is that right ?

Yes

**Pull request merged**
